doctrine:
    dbal:
        driver: 'pdo_pgsql'
        host: "%env(DB_HOST)%"
        port: "%env(DB_PORT)%"
        dbname: "%env(DB_NAME)%"
        user: "%env(DB_ROOT_USER)%"
        password: "%env(DB_ROOT_PASSWORD)%"
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Domain:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Model'
                prefix: 'Domain\Model'
                alias: App
